### PR TITLE
Michaelamann parallel r

### PR DESCRIPTION
**Pull request by michaelamann**
R parallel is ready to go!

### CODE REVIEW

**Comment by ethangyllenhaal** [comment]
Can't properly comment on notebook because GitHub doesn't render it for comments, so listed here. Also, this is all about the text, doing during PM so can't log on to try:

First paragraph doesn't end properly for me, second doesn't start properly: "....by creating unified sty", "processors and multiple nodes...."

First list of items has oddly places asterisks in them for me, are they supposed to be arrows?: "Choose how you want to parallelize your code * set the type of parallelization with the plan() object."

Mention that this is designed for wheeler, and link to wheeler's jupyterhub portal.

IMO add packages to table of contents (can be "0. Packages")


**Section 1:**

General: lots of line starts aren't capitalized

First line: "examaple" -> "example", also, I don't think 0.5 seconds is that slow haha

"Setup and loop in serial" --> "Setting up and running loop in serial" (also "thta" --> "that" in next line)

Next code block: "timestampe" -> "timestamp", 

Stuff under "Choose which part of the code you would like to run in parallel": Be clear that this step is generating the command set, not running anything. Maybe even change the title. I think add a longer description of what exactly "future()" is, not everyone using R knows about objects I imagine. Also, in code block, replace "Elapsed time (seconds) for for-loop" with "Elapsed time (seconds) for planning command set"

Same block, mention the appendix and your basic findings (e.g. tasks longer than e.g. 1 second are better in parallel)


**Section 2:**

Add a reference to tidyverse... no need to explain it all, just to prevent confusion for non-tidy-converts

Under setup: "comput" -> "compute"

Be clear about why evaluation isn't needed, I assume it's because 


**Section 3:**

"batchtools.torque.tmpl" I think each \#PBS bit is supposed to be it's own line, no? Whole line looks very weird


**Appendix:**

end of first line: "allows to" --> "allows you to"

Under "Scenario 1 Cost of setup for many iterations", maybe mention that setup is done in serial, hence why it's independent of core \#

I'll get to re-confirming everything runs well from a blank directory once wheeler is back up!!

**Comment by ethangyllenhaal** [comment]
Under Packages, Make sure to specify that the target directory must already exist.

I wasn't able to load the data for Hrms/Bayesian section, but also didn't have the torque file because the formatting in the notebook was weird. Errors for the block:

Warning message in readChar(con, 5L, useBytes = TRUE):
“cannot open compressed file 'hmsc_setup.RData', probable reason 'No such file or directory'”

Error in readChar(con, 5L, useBytes = TRUE): cannot open the connection
Traceback:
1. load("hmsc_setup.RData")
2. readChar(con, 5L, useBytes = TRUE)


To run the appendix, I needed "labeling", "farver" installed. It worked once I installed and loaded them on my own.

**Comment by ethangyllenhaal** [comment]
Ran the Bayesian portion. One error was another obscure dependency to install: fs. The bigger problem was the following error when running "Rerunning bayesian models in parallel using future.batchtools package". I checked and the .log file didn't exist, but the directories leading up to it did:

Error: Log file '/users/egyllenh/test/.future/20210728_115851-pV6ygu/batchtools_1242760698/logs/joba228d954f1949690a450d2b2a6db6bd4.log' for job with id 1 not available
Traceback:

1. value(y)
2. value.list(y)
3. resolve(y, result = TRUE, stdout = stdout, signal = signal, force = TRUE)
4. resolve.list(y, result = TRUE, stdout = stdout, signal = signal, 
 .     force = TRUE)
5. value(obj, stdout = FALSE, signal = FALSE)
6. value.Future(obj, stdout = FALSE, signal = FALSE)
7. result(future)
8. result.BatchtoolsFuture(future)
9. await(future, cleanup = FALSE)
10. loggedOutput(future)
11. loggedOutput.BatchtoolsFuture(future)
12. getLog(id = jobid, reg = reg)
13. extractLog(readLog(id, reg = reg), id)
14. readLog(id, reg = reg)
15. stopf("Log file '%s' for job with id %i not available", log.file, 
  .     id$job.id)


Other notes:

Mention this tutorial is designed for wheeler (hence the 8 cores)

Under tidyverse section: "# this time we do no not need to the evauluation" --> change to evaluation

**Comment by ethangyllenhaal** [comment]
Conda: I don't think activating the environment does anything for you. Pretty sure the way to go is select that option when spawning a notebook

Section 3:
I assume the sample data is downloaded by the new code, right?

Explicitly say the .tmpl file has to be made by the user, also "batchtools.torque.tmpl file needed in the same directory" should end with "same directory as the notebook you are using"

Headers aren't over their respective code blocks

I think you need to specify the path to load hmsc_setup.RData (I definitely had to to get it to work) and change to the working directory for the .tmpl file.

For some reason the first example took way longer than 130 seconds for me (~800)

Also, last but certainly not least, Hrms loading is still failing for batchtools....

**Comment by ethangyllenhaal** [comment]
Checked and looks good pending prior changes. One note, I needed to use the (in your notebook) commented out line that has the libpath argument

**Review by ethangyllenhaal — APPROVED** [review]
Looks good!

**Review by gmfricke — CHANGES_REQUESTED** [review]
I think the table of contents needs to be updated.

**Review by gmfricke — APPROVED** [review]
Well done.

**Pull request merged**
