### PR TITLE
Singularity QuickByte

### PR DESCRIPTION
**Pull request by gmfricke**

### CODE REVIEW

**Comment by liphardt** [comment]
Ends kind of abruptly after the section about mapping directories.

**Comment by ceodspspectrum** [comment]
@savinshynu Hi Savin, if this looks good, can you please approve it and merge? Thank you

**Comment by savinshynu** [comment]
The suggested changes are not implemented in the html file.

**Comment by liphardt** [comment]
I will convert this to Markdown today and implement Savin's comments.

**Comment by liphardt** [comment]
@gmfricke When I convert to markdown I am going to lose all the color coding. Is that okay? Or do we want to just keep this one in html?

**Comment by gmfricke** [comment]
That’s completely fine.

**Pull request closed without merging**
