### PR TITLE
Changed Matlab version

### PR DESCRIPTION
**Pull request by vsurjadidjaja**
Changed R2018b to R2019a in the text.
TODO: embedded images that say R2018b may need to be changed as well.

### CODE REVIEW

**Comment by gmfricke** [comment]
I think Schuyler did this (?)

On Oct 22, 2019, at 2:48 PM, liphardt <notifications@github.com<mailto:notifications@github.com>> wrote:


@liphardt approved this pull request.

@gmfricke<https://github.com/gmfricke> @vsurjadidjaja<https://github.com/vsurjadidjaja> I don't think we have matlab R2019a installed on Xena yet. Do we want to do that?

**Comment by liphardt** [comment]
I installed R2019a on Taos, but never on Xena. Last one I installed on Xena was 2018b, which is the newest one we have on there.

**Comment by gmfricke** [comment]
OK, we should put it on the list.

On Oct 22, 2019, at 3:54 PM, liphardt <notifications@github.com<mailto:notifications@github.com>> wrote:

I installed R2019a on Taos, but never on Xena. Last one I installed on Xena was 2018b, which is the newest one we have on there.

**Comment by liphardt** [comment]
Sure, I can take care of that this week if it is high on the list.

**Pull request merged**
