### PR TITLE
Paraview Quickbyte

### PR DESCRIPTION
**Pull request by gmfricke**

### CODE REVIEW

**Comment by liphardt** [comment]
delete third method relating to X-forwarding. Not functional.

**Comment by gmfricke** [comment]
@ceodspspectrum delete the 3rd option if it doesnt work

**Comment by gmfricke** [comment]
@ceodspspectrum Hi Savin, could you delete the 3rd option if it hasn't been deleted already?

**Comment by savinshynu** [comment]
Hi Matthew,
I have deleted the X forwarding method.

**Pull request merged**
