### PR TITLE
Michaelamann metabarcoding

### PR DESCRIPTION
**Pull request by michaelamann**

### CODE REVIEW

**Comment by ethangyllenhaal** [comment]
General comment, for anything other than setting up directories and conda environments, assume they are running it from a script (e.g. no "cd $src"). Assume directories and conda environments are done before scripts, so no need for variables like $src to be set off right away. This will often mean any conda stuff is activated and run on a node.

When downloading data, the folder name after unzipping is "MiSeq_SOP". Also, need to specify to make fastq directory and move fastqs there.mv and change "gzip >fa" to "gzip *fastq".

Qiime:
Conda environment year doesn't match comment
The denoising stats are named inconsistently, they're output as "stats-dada2.qza" then attempted to be called as "denoising-stats.qza" in metadata tabulate

usearch:
Probably add a line to re-zip all the fastqs after merging.

Didn't try Mothur yet on MM's request.

For all, it is worth giving approx runtimes. It's ~5 mins for qiime, ~1 min for usearch. Could be worth just saying "all take less than X minutes", just something to let people know they can queue the test on debug. May also be worth saying how long full datasets could take when you write it up.

**Comment by gmfricke** [comment]
@ethangyllenhaal please add your review

**Review by ethangyllenhaal — CHANGES_REQUESTED** [review]
You should specify what resources a user is using for this (and in turn for their own work with real, big datasets). Currently it looks like it'd be an interactive job. We don't want them doing it on a head node. I prefer to assume they are running it in a job script, with conda setup done independently (which means it wouldn't be activated in the same block it's created)

Mothur worked, so I assume you'll finish up annotations etc

**Review by ethangyllenhaal — CHANGES_REQUESTED** [review]
Minimum: separate conda env creation from activation
Ideal: Add "how to run" section mentioning approx resource/time reqs, how to run as a submission script

**Review by gmfricke — APPROVED** [review]
Breaking out into PBS and install sections will have to happen at a later time,

**Pull request merged**
