### PR TITLE
Use Scratch on Taos

### PR DESCRIPTION
**Pull request by gmfricke**
The previous version had all the IO on the home directory

### CODE REVIEW

**Comment by gmfricke** [comment]
@liphardt Please try running this and see if it works. You might want to do something similar for the wheeler script.

**Comment by liphardt** [comment]
@gmfricke I am testing this now to make sure it works the way we want. I added an additional couple of steps to create a directory for the additional output of an Orca job, copy that additional output to the directory, and then clean the scratch directory after. Does this seem reasonable? I can modify the Wheeler PBS script to do the same.

**Comment by gmfricke** [comment]
@liphardt It does seem reasonable. I think we are working from the same scratch PBS example :) It always makes me nervous to include anything in a quickbyte that automates the deletion of a directory. There is a change, even if remote, that scract/$prefix already exists and contains data the user cares about. I think you should add a scratch directory already exists check. Something like if [ -d $scratch_dir/$prefix/ ] then exit with an error. Alternatively, you can use mktemp on scratch which makes some (maybe?) guarantees about directory uniqueness.

**Comment by liphardt** [comment]
@gmfricke Yeah, that is a really good point. I will work on setting that up.

**Comment by gmfricke** [comment]
@liphardt Just checking the status on this.

**Comment by liphardt** [comment]
@gmfricke Sorry. I will get it done this week.

**Comment by liphardt** [comment]
@gmfricke I added the temporary directory in scratch to work out of.

**Review by liphardt — APPROVED** [review]
This looks reasonable to me. I have tested the code previously.

**Pull request merged**
